name = "JavaCall"
uuid = "494afd89-becb-516b-aafa-70d2670c0337"
version = "0.7.2"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WinReg = "1b915085-20d7-51cf-bf83-8f477d6f5128"

[compat]
julia = "1"
