name = "JavaCall"
uuid = "494afd89-becb-516b-aafa-70d2670c0337"
version = "0.7.4"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
WinReg = "1b915085-20d7-51cf-bf83-8f477d6f5128"

[compat]
DataStructures = "0.17"
WinReg = "0.3.1"
julia = "1"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Taro = "61d0e4fa-4e73-5030-88a9-ae4c27b203dd"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[targets]
test = ["Taro", "Pkg", "Test","DataFrames"]
