name = "JProxies"
uuid = "5876e902-ba5b-11ea-3851-9ff53fa1e944"
version = "0.0.1"

[deps]
JavaCall = "494afd89-becb-516b-aafa-70d2670c0337"

[compat]
JavaCall = "0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
